source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 9
