source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 0
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 9
