source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10 512 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20 512 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30 512 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40 512 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50 512 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 16 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 32 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 64 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 128 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 256 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 384 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 60 512 19
