source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 20
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 21
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 22
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 23
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 24
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 25
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 26
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 27
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 28
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 29
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 30
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 31
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 32
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 33
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 34
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 35
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 36
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 37
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 38
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 39
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 40
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 41
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 42
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 43
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 44
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 45
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 46
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 47
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 48
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 49
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py CartPole-v1 CartPole-v1 50
