source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 1
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 2
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 3
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 4
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 5
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 6
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 7
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 8
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 9
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 10
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 11
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 12
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 13
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 14
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 15
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 16
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 17
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 18
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 19
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 20
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 21
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 22
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 23
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 24
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 25
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 26
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 27
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 28
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 29
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 30
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 31
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 32
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 33
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 34
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 35
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 36
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 37
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 38
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 39
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 40
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 41
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 42
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 43
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 44
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 45
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 46
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 47
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 48
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 49
source /data/kimchm/conda/bin/activate pyrl && python3 run_dopa.py LunarLander-v3 LunarLander-v3 50
